// ============== Copyright (c) 2025 Monochrome Games ============== \\

#ifndef SHARED_ZOMBIEPANIC_ACHIEVEMENTS
#define SHARED_ZOMBIEPANIC_ACHIEVEMENTS
#pragma once

enum EAchievements
{
	ONE_OF_US = 0,
	FIRST_TO_DIE,
	PANIC_ATTACK,
	KILLS_PISTOL,
	KILLS_SHOTGUN,
	KILLS_RIFLE,
	KILLS_REVOLVER,
	KILLS_SATCHEL,
	KILLS_TNT,
	KILLS_CROWBAR,
	KILLS_ZOMBIE,
	YOU_WILL_DIE_WITH_ME,
	UNSAFE_HANDLING,
	I_FELL,
	FIRST_SURVIVAL,
	FIRST_OBJECTIVE,
	JACKOFTRADES,
	CLOCKOUT,
	PANICRUSH,
	FLEEESH,
	ZOMBIEDESSERT,
	SCREAM4ME,
	ITS_A_MASSACRE,
	THE_ATEAM,
	LASTMANSTAND,
	MARATHON,
	PARTNERINCRIME,
	RABBITBEAST,
	PLAY_ALL_SURVIVAL,
	PLAY_ALL_OBJECTIVE,
	PANIC_100,
	INLINEP2,
	PUMPUPSHOTGUN,
	CUTYOUDOWN,
	CHILDOFGRAVE,
	DIE_BY_DOOR,
	ZMASH,
	TABLE_FLIP,
	KILLS_MP5,
	PARTOFHORDE,

	ACHV_MAX
};

#endif