name: CI/CD

on: [push, pull_request]

env:
  BUILD_TYPE: Release
  GAME_NAME: Zombie-Panic
  MOD_NAME: zp

jobs:
  linux:
    name: Linux-x86
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Install G++ Multilib & 32 bit OpenGL library
        run: |
          sudo dpkg --add-architecture i386
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install -y g++-11-multilib libgcc-s1:i386 libstdc++6:i386 libatomic1:i386 libgl1-mesa-dev:i386
         
      - name: Install g++-9
        run: |
          sudo apt-get install gcc-9 g++-9
          export PATH="$PATH:/usr/bin/g++-9"  # Add g++-9 to the PATH

      - name: Compile using g++-9
        run: |
          g++-9 -c your_source_file.cpp # Compile with g++-9
          g++-9 -o your_executable your_source_file.o # Link and create executable

      - uses: lukka/get-cmake@latest
      
      - name: Configure
        run: >
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{env.GAME_NAME}}/${{env.MOD_NAME}}
          -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/cmake/ToolchainLinuxGCC9.cmake
        
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j3
        
      - name: Install
        run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux-x86
          path: ${{env.GAME_NAME}}
        
  win32:
    name: Win32
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - uses: lukka/get-cmake@latest
      
      - name: Configure
        run: >
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{env.GAME_NAME}}/${{env.MOD_NAME}}
          -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/cmake/WinXPSupport.cmake -A Win32
        
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j3
        
      - name: Install
        run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Win32
          path: ${{env.GAME_NAME}}
