name: CI/CD

on: [push, pull_request]

jobs:
  linux-steam-runtime:
    name: Linux-x86 (Steam Runtime)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: docker://registry.gitlab.steamos.cloud/steamrt/scout/sdk/i386:latest
        with:
          args: ./github_actions_steam_runtime_build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux-x86-Steam-Runtime
          path: |
            build/client.so
            build/hl.so